# Generated by Django 5.2.4 on 2025-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('FullStack', 'FullStack'), ('Web3', 'Web3'), ('Healthcare', 'Healthcare'), ('Technology', 'Technology'), ('Economy', 'Economy'), ('Business', 'Business'), ('Sports', 'Sports'), ('Lifestyle', 'Lifestyle')], max_length=255),
        ),
    ]
